<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE top_outfielders[
    <!ELEMENT top_outfielders (jugador*)>
    <!ELEMENT jugador (nombre, equipo, estadisticas_bateo, defensa)>
    <!ATTLIST jugador posicion CDATA #REQUIRED>

    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT equipo (#PCDATA)>

    <!ELEMENT estadisticas_bateo (max_exit_velocity, avg_exit_velocity, distance)>
    <!ELEMENT max_exit_velocity (#PCDATA)>
    <!ELEMENT avg_exit_velocity (#PCDATA)>
    <!ELEMENT distance (#PCDATA)>

    <!ELEMENT defensa (oaa, outfield_jump, arm_strength )>

    <!ELEMENT oaa (#PCDATA)>
    <!ELEMENT outfield_jump (#PCDATA)>
    <!ELEMENT arm_strength (#PCDATA)>    
    
]>

<top_outfielders>
    <jugador posicion="LF">
        <nombre>Kyle Stowers</nombre>
        <equipo>Miami Marlins</equipo>
        <estadisticas_bateo>
            <max_exit_velocity>113.7</max_exit_velocity>
            <avg_exit_velocity>91.1</avg_exit_velocity>
            <distance>395</distance>
        </estadisticas_bateo>
        <defensa>
            <oaa>2</oaa>
            <outfield_jump>0.5</outfield_jump>
            <arm_strength>87</arm_strength>
        </defensa>
    </jugador>

    <jugador posicion="RF">
        <nombre>Riley Greene</nombre>
        <equipo>Detroit Tigers</equipo>
        <estadisticas_bateo>
            <max_exit_velocity>115.1</max_exit_velocity>
            <avg_exit_velocity>89.9</avg_exit_velocity>
            <distance>397</distance>
        </estadisticas_bateo>
        <defensa>
            <oaa>4</oaa>
            <outfield_jump>1.2</outfield_jump>
            <arm_strength>88</arm_strength>
        </defensa>
    </jugador>

    <jugador posicion="CF">
        <nombre>Ram√≥n Laureano</nombre>
        <equipo>San Diego Padres</equipo>
        <estadisticas_bateo>
            <max_exit_velocity>112.7</max_exit_velocity>
            <avg_exit_velocity>90.3</avg_exit_velocity>
            <distance>398</distance>
        </estadisticas_bateo>
        <defensa>
            <oaa>3</oaa>
            <outfield_jump>1.0</outfield_jump>
            <arm_strength>93</arm_strength>
        </defensa>
    </jugador>

   
</top_outfielders>

