<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE top_entrenadores[
    <!ELEMENT top_entrenadores (entrenador*)>
    <!ELEMENT entrenador (nombre, equipo?, experiencia, victorias, derrotas)>

    <!ELEMENT nombre (#PCDATA)>

    <!ELEMENT equipo (#PCDATA)>
    <!ATTLIST equipo activo (si|no) #REQUIRED>

    <!ELEMENT experiencia (#PCDATA)>
    <!ELEMENT victorias (#PCDATA)>
    <!ELEMENT derrotas (#PCDATA)>  
]>

<top_entrenadores>
    <entrenador>
        <nombre>Torey Lovullo</nombre>
        <equipo activo="si">Arizona Diamondbacks</equipo>
        <experiencia>5</experiencia>
        <victorias>112</victorias>
        <derrotas>102</derrotas>
    </entrenador>
    <entrenador>
        <nombre>Brian Snitker</nombre>
        <equipo activo="si">Atlanta Braves</equipo>
        <experiencia>9</experiencia>
        <victorias>112</victorias>
        <derrotas>98</derrotas>
    </entrenador>
    <entrenador>
        <nombre>Alex Cora</nombre>
        <equipo activo="si">Baltimore Orioles</equipo>
        <experiencia>7</experiencia>
        <victorias>112</victorias>
        <derrotas>98</derrotas>
    </entrenador>
    <entrenador>
        <nombre>Craig Counsell</nombre>
        <equipo activo="si">Boston Red Sox</equipo>
        <experiencia>10</experiencia>
        <victorias>51</victorias>
        <derrotas>57</derrotas>
    </entrenador>
    <entrenador>
        <nombre>Bud Black</nombre>
        <equipo activo="si">Colorado Rockies</equipo>
        <experiencia>17</experiencia>
        <victorias>76</victorias>
        <derrotas>138</derrotas>
    </entrenador>
    <entrenador>
        <nombre>Dave Roberts</nombre>
        <equipo activo="si">Los Angeles Angels</equipo>
        <experiencia>9</experiencia>
        <victorias>63</victorias>
        <derrotas>44</derrotas>
    </entrenador>
    <entrenador>
        <nombre>Skip Schumaker</nombre>
        <equipo activo="si">Los Angeles Dodgers</equipo>
        <experiencia>2</experiencia>
        <victorias>39</victorias>
        <derrotas>67</derrotas>
    </entrenador>
    <entrenador>
        <nombre>Aaron Boone</nombre>
        <equipo activo="si">New York Yankees</equipo>
        <experiencia>7</experiencia>
        <victorias>126</victorias>
        <derrotas>90</derrotas>
    </entrenador>
    <entrenador>
        <nombre>Mark Kotsay</nombre>
        <equipo activo="no"></equipo>
        <experiencia>3</experiencia>
        <victorias>88</victorias>
        <derrotas>128</derrotas>
    </entrenador>
    <entrenador>
        <nombre>Mike Shildt</nombre>
        <equipo activo="si">San Diego Padres</equipo>
        <experiencia>8</experiencia>
        <victorias>114</victorias>
        <derrotas>102</derrotas>
    </entrenador>
</top_entrenadores>
